---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vidafit9/public_html/vp360/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/date > $DEPLOYPATH/deploy_log.txt
    - /bin/echo "DEPLOYMENT SUCCESSFUL - Version without htaccess" >> $DEPLOYPATH/deploy_log.txt
