---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vidafit9/public_html/vp360/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/date > $DEPLOYPATH/deploy_log.txt
    - /bin/echo "Deployed to $DEPLOYPATH" >> $DEPLOYPATH/deploy_log.txt
